version: "3.8"

services:
  lanki-note-service:
    depends_on:
      - lanki-db
    image: "ghcr.io/imko/lanki-backend/note-service:0.0.1-snapshot"
    container_name: lanki-note-service
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lanki-db:5432/lanki

  lanki-db:
    image: postgres
    container_name: lanki-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lanki
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d lanki
      interval: 10s
      timeout: 3s
      retries: 5

  lanki-redis:
    image: "redis:7.0"
    container_name: lanki-redis
    ports:
      - "6379:6379"