server:
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: note-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/lanki
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect